{% set name = "flake8-sfs" %}
{% set version = "0.0.4" %}
{% set sha256 = "81414c8041531e173f3285f2c0552b8e25aaf3b973e17ea33c3b0719385c93b8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - flake8 >=3

test:
  commands:
    - 'flake8 --version | grep flake8-sfs:'

about:
  home: https://github.com/peterjc/flake8-sfs
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: Extension for flake8 for validating Python String Formatting Style (SFS)
  dev_url: https://github.com/peterjc/flake8-sfs
  description: |
    For historical reasons, the Python programming language has accumlated
    multiple ways to do string formatting. This flake8 plugin exists to let
    you define which of these styles your project allows from within the
    flake8 plugin ecosystem. You might use this via a git pre-commit hook,
    or as part of your continuous integration testing.

extra:
  recipe-maintainers:
    - peterjc
